java.compatibility=8
kotlin.compatibility=2.0.0

kdoc.olderVersions=
kdoc.artifactId=kdoc
kdoc.projects=*


pom.groupId=com.apollographql.java
pom.version=1.0.0-alpha.0-SNAPSHOT
pom.description=Java support for Apollo Kotlin
pom.vcsUrl=https://github.com/apollographql/apollo-kotlin-java-support
pom.developer=Apollo Kotlin Java Support contributors
pom.license=MIT
checkDependenciesCompatibility=false